### ISSUE TITLE
Not functional using latest Mongoose

### ISSUE THREAD

**Issue by malammar** [Maheshkumar-Kakade/mongoose-aggregate-paginate#13]
Sample code:

`
	var aggregate = Name.aggregate();
	aggregate.match(query)
		.group(
		{
			_id: "$name1",
			$push:
			{
				$sum: 1
			}
		});
	var options = {
		page: page,
		limit: perPage
	};`

`	Name.aggregatePaginate(aggregate, options, function(err, results, pageCount, count)
	{
		if (err)
		{
			res.send(err);
		}
		else
		{
			res.json(results);
		}
	});
`

Returns:

`Mongoose: Names.aggregate()
TypeError: Cannot read property 'readPreference' of undefined
    at Collection.aggregate (C:\dev\projects\yousay\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\collection.js:1587:17)
    at NativeCollection.(anonymous function) [as aggregate] (C:\dev\projects\yousay\server\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:129:21)
    at Function.aggregate (C:\dev\projects\yousay\server\node_modules\mongoose\lib\model.js:1640:36)
    at Object.handle (C:\dev\projects\yousay\server\app\routes\names.js:67:23)
    at next_layer (C:\dev\projects\yousay\server\node_modules\express\lib\router\route.js:103:13)
    at next_layer (C:\dev\projects\yousay\server\node_modules\express\lib\router\route.js:81:14)
    at Route.dispatch (C:\dev\projects\yousay\server\node_modules\express\lib\router\route.js:107:5)
    at C:\dev\projects\yousay\server\node_modules\express\lib\router\index.js:195:24
    at Function.proto.process_params (C:\dev\projects\yousay\server\node_modules\express\lib\router\index.js:251:12)
    at next (C:\dev\projects\yousay\server\node_modules\express\lib\router\index.js:189:19)`

**Comment by Maheshkumar-Kakade** [comment]
I will check it on latest one.

**Comment by Maheshkumar-Kakade** [comment]
Just ran it module against latest mongoose i.e 4.7.2 and it is working fine. Will you please share more details like
1. Version
2. Sample Code where it was not working

**Comment by Maheshkumar-Kakade** [comment]
Closing issue as no one able to reproduce it.
